title: Hongyi Dong
description: Hongyi Dong's research, design work, and writing.
baseurl: ""
url: ""

permalink: /blog/:title/

plugins:
  - jekyll-feed

encoding: UTF-8
strict_front_matter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

sass:
  sass_dir: assets/css

# defaults:
#   - 
#     scope:
#       path: 
#       type: posts 
#     values:
#         layout: post
