academia:
- {
  title: 'Youth Online Privacy Conversations',
  subtitle: 'Sharing Stories and Making Sense of Privacy',
  year: 2026,
  folder: 'online-communities',
  file: 'academia/online-communities'
}
- {
  title: 'A Privacy Literacy Toolkit',
  subtitle: 'Empowering Librarians and Communities',
  year: '2023-?',
  folder: 'privacy-toolkit',
  file: 'academia/privacy-toolkit'
}
- {
  title: 'Explorations and Other Projects',
  subtitle: 'Ideas in the Making',
  year: '2023-?',
  folder: 'explorations',
  file: 'academia/explorations'
}

industry:
- {
  title: 'Evalueserve',
  subtitle: 'Design and Consulting',
  year: 2019,
  folder: 'evs',
  file: 'industry/evs'
}
- {
  title: 'Carolina Digital Repository',
  subtitle: 'The Two-Year Journey of a Digital Migration',
  year: 2017,
  folder: 'cdr',
  file: 'industry/cdr'
}
- {
  title: 'nVisium',
  subtitle: 'Designing for Application Security',
  year: 2014,
  folder: 'nv',
  file: 'industry/nv'
}
- {
  title: 'Munis Delivery App',
  subtitle: 'My First Journey Into User Experience',
  year: 2013,
  folder: 'tyler',
  file: 'industry/tyler'
}
- {
  title: 'Advanced Structure and Composites Center',
  subtitle: 'A Rebranding Campaign Led by Students',
  year: 2012,
  folder: 'ascc',
  file: 'industry/ascc'
}

socials:
- {
  icon: 'mastodon',
  label: 'Mastodon',
  link: 'https://mastodon.social/@leslied'
}
- {
  icon: 'linkedin',
  label: 'LinkedIn',
  link: 'https://www.linkedin.com/in/hydong'
}
- {
  icon: 'scholar',
  label: 'Google Scholar',
  link: 'https://scholar.google.com/citations?hl=en&user=lzJVIZIAAAAJ'
}
- {
  icon: 'blog',
  label: 'Blog',
  link: '/blog'
}

